version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # Cambia a algo más seguro
      MYSQL_DATABASE: mrdb                 # Base de datos que se creará
      MYSQL_USER: user                     # Usuario de la base de datos
      MYSQL_PASSWORD: userpassword         # Contraseña del usuario
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./app
    container_name: web_app
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_NAME: mrdb
      DB_USER: user
      DB_PASSWORD: userpassword

volumes:
  db_data:
